### ISSUE TITLE
This is the best react-redux-typescript boilerplate ever

### ISSUE THREAD

**Issue by meds** [kamataryo/react-redux-typescript-boilerplate#4]
Not an issue but I didn't know how to tell you, this is by far the best boilerplate I've found online.

I've been beating my head over all the bullshit boilerplates out there packed full of nonesense which don't apply or poor implementations of components (for example [component name]/index.ts like wtf?).

Good job on this light weight boilerplate!

**Comment by kamataryo** [comment]
Hi, thank you for the interest in this project.
This boilerplate was built for my daily work, but I hope it will be helpful for you too!
Feel free to raise issues or PRs if you find any problems.
